import bcrypt from "bcryptjs";
import mongoose from "mongoose";
import { connectDatabase } from "../config/db.js";
import { Assessment } from "../models/Assessment.js";
import { AssessmentAttempt } from "../models/AssessmentAttempt.js";
import { AssessmentInvitation } from "../models/AssessmentInvitation.js";
import { Application } from "../models/Application.js";
import { BillingProfile } from "../models/BillingProfile.js";
import { Candidate } from "../models/Candidate.js";
import { CandidatePrivacySettings } from "../models/CandidatePrivacySettings.js";
import { Company } from "../models/Company.js";
import { Coupon } from "../models/Coupon.js";
import { CreditBalance } from "../models/CreditBalance.js";
import { CreditTransaction } from "../models/CreditTransaction.js";
import { IntegrityEvent } from "../models/IntegrityEvent.js";
import { Interview } from "../models/Interview.js";
import { Invoice } from "../models/Invoice.js";
import { Job } from "../models/Job.js";
import { Notification } from "../models/Notification.js";
import { PaymentMethod } from "../models/PaymentMethod.js";
import { ProcessedWebhook } from "../models/ProcessedWebhook.js";
import { QuestionBankItem } from "../models/QuestionBankItem.js";
import { Recruiter } from "../models/Recruiter.js";
import { Resume } from "../models/Resume.js";
import { SavedJob } from "../models/SavedJob.js";
import { Subscription } from "../models/Subscription.js";
import { SubscriptionPlan } from "../models/SubscriptionPlan.js";
import { User } from "../models/User.js";
import { UsageRecord } from "../models/UsageRecord.js";
import { CandidateSession } from "../models/CandidateSession.js";

async function seed() {
  await connectDatabase();
  await Promise.all([
    ProcessedWebhook.deleteMany({}),
    Invoice.deleteMany({}),
    CreditTransaction.deleteMany({}),
    CreditBalance.deleteMany({}),
    PaymentMethod.deleteMany({}),
    BillingProfile.deleteMany({}),
    Subscription.deleteMany({}),
    SubscriptionPlan.deleteMany({}),
    Coupon.deleteMany({}),
    IntegrityEvent.deleteMany({}),
    AssessmentAttempt.deleteMany({}),
    AssessmentInvitation.deleteMany({}),
    Assessment.deleteMany({}),
    QuestionBankItem.deleteMany({}),
    Application.deleteMany({}),
    Interview.deleteMany({}),
    Job.deleteMany({}),
    Company.deleteMany({}),
    Recruiter.deleteMany({}),
    Notification.deleteMany({}),
    SavedJob.deleteMany({}),
    Resume.deleteMany({}),
    CandidateSession.deleteMany({}),
    CandidatePrivacySettings.deleteMany({}),
    Candidate.deleteMany({}),
    User.deleteMany({}),
  ]);

  const passwordHash = await bcrypt.hash("Recruiter@123", 10);
  const candidatePasswordHash = await bcrypt.hash("Candidate@123", 10);
  const user = await User.create({
    name: "Riya Sharma",
    email: "recruiter@novaedge.ai",
    passwordHash,
    role: "recruiter",
  });

  const recruiter = await Recruiter.create({
    userId: user._id,
    name: "Riya Sharma",
    email: "recruiter@novaedge.ai",
    phone: "+1 415 555 0132",
    position: "Senior Talent Partner",
  });

  const company = await Company.create({
    recruiterId: recruiter._id,
    name: "NovaEdge AI",
    logo: "",
    website: "https://novaedge.ai",
    industry: "Artificial Intelligence",
    companySize: "201-500 employees",
    foundedYear: 2018,
    email: "hello@novaedge.ai",
    phone: "+1 415 555 0199",
    headquarters: "San Francisco, CA",
    officeLocations: ["San Francisco, CA", "Austin, TX", "Remote"],
    description:
      "NovaEdge AI builds workflow automation products for fast-moving teams. We care about practical AI, strong product execution, and shipping systems that make people more effective every day across customer support, operations, and hiring workflows.",
    mission: "Make advanced automation feel reliable, useful, and human-centered.",
    culture: "Curious, high-ownership, feedback-driven, and deeply collaborative.",
    benefits: ["Health coverage", "Remote flexibility", "Learning budget", "Equity"],
    socialLinks: {
      linkedin: "https://linkedin.com/company/novaedge-ai",
      other: ["https://x.com/novaedgeai"],
    },
    verificationStatus: "Verified",
    profileCompletion: 100,
  });

  recruiter.companyId = company._id;
  await recruiter.save();

  const candidateUsers = await User.insertMany([
    {
      name: "Aarav Patel",
      email: "aarav.patel@example.com",
      passwordHash: candidatePasswordHash,
      role: "candidate",
    },
    {
      name: "Maya Chen",
      email: "maya.chen@example.com",
      passwordHash: candidatePasswordHash,
      role: "candidate",
    },
  ]);

  const candidates = await Candidate.insertMany([
    {
      userId: candidateUsers[0]._id,
      name: "Aarav Patel",
      email: "aarav.patel@example.com",
      phone: "+1 202 555 0101",
      professionalTitle: "Frontend Engineer",
      summary: "Frontend engineer with a strong focus on React, accessibility, and design systems.",
      location: "Austin, TX",
      skills: ["React", "JavaScript", "CSS", "TypeScript", "Git"],
      education: [{ institution: "UT Austin", degree: "B.Tech", field: "Computer Science", graduationYear: 2021 }],
      experience: [
        { company: "BlueHill", role: "Frontend Developer", years: 2, description: "Built internal dashboards." },
        { company: "LaunchGrid", role: "Software Engineer", years: 1.5, description: "Improved customer-facing flows." },
      ],
      projects: [{ name: "Hiring Insights", description: "Analytics dashboard project", technologies: ["React", "Recharts"] }],
      certifications: ["AWS Cloud Practitioner"],
      languages: ["English", "Hindi"],
      resumeUrl: "https://example.com/resumes/aarav-patel.pdf",
      availability: "2 weeks",
      city: "Austin",
      state: "Texas",
      country: "United States",
      yearsOfExperience: 3,
      employmentStatus: "Actively interviewing",
      socialLinks: {
        linkedin: "https://linkedin.com/in/aarav-patel",
        github: "https://github.com/aaravpatel",
        portfolio: "https://aarav.dev",
        website: "",
        other: [],
      },
      jobPreferences: {
        preferredRoles: ["Frontend Engineer", "UI Engineer"],
        preferredIndustries: ["SaaS", "AI"],
        preferredLocations: ["Austin, TX", "Remote"],
        remotePreference: "Hybrid",
        employmentTypes: ["Full-time"],
        expectedSalary: 115000,
        currency: "USD",
        noticePeriod: "2 weeks",
        availableJoiningDate: new Date(Date.now() + 14 * 86400000),
        willingToRelocate: false,
        openToRecruiterDiscovery: true,
      },
    },
    {
      userId: candidateUsers[1]._id,
      name: "Maya Chen",
      email: "maya.chen@example.com",
      phone: "+1 202 555 0102",
      professionalTitle: "Full Stack Developer",
      summary: "Full stack developer with experience building SaaS products and scalable APIs.",
      location: "Seattle, WA",
      skills: ["Node.js", "React", "MongoDB", "TypeScript", "Docker"],
      education: [{ institution: "UW", degree: "MS", field: "Software Engineering", graduationYear: 2020 }],
      experience: [{ company: "Northline", role: "Full Stack Engineer", years: 4, description: "Owned platform services." }],
      projects: [{ name: "Candidate Ranker", description: "Resume ranking tool", technologies: ["Node.js", "OpenAI API"] }],
      certifications: ["MongoDB Developer"],
      languages: ["English", "Mandarin"],
      resumeUrl: "https://example.com/resumes/maya-chen.pdf",
      availability: "Immediate",
      city: "Seattle",
      state: "Washington",
      country: "United States",
      yearsOfExperience: 4,
      employmentStatus: "Open to opportunities",
      socialLinks: {
        linkedin: "https://linkedin.com/in/maya-chen",
        github: "https://github.com/mayachen",
        portfolio: "https://maya.build",
        website: "",
        other: [],
      },
      jobPreferences: {
        preferredRoles: ["Full Stack Developer", "Platform Engineer"],
        preferredIndustries: ["Developer Tools", "AI"],
        preferredLocations: ["Seattle, WA", "Remote"],
        remotePreference: "Remote",
        employmentTypes: ["Full-time"],
        expectedSalary: 135000,
        currency: "USD",
        noticePeriod: "Immediate",
        availableJoiningDate: new Date(Date.now() + 3 * 86400000),
        willingToRelocate: true,
        openToRecruiterDiscovery: true,
      },
    },
    {
      name: "Leo Martinez",
      email: "leo.martinez@example.com",
      phone: "+1 202 555 0103",
      professionalTitle: "Product Designer",
      summary: "Designer focused on product strategy, UX systems, and research-backed iteration.",
      location: "Remote",
      skills: ["Figma", "User Research", "Design Systems", "Prototyping"],
      education: [{ institution: "Parsons", degree: "B.Des", field: "Product Design", graduationYear: 2019 }],
      experience: [{ company: "FrameFlow", role: "Product Designer", years: 5, description: "Led platform UX improvements." }],
      projects: [{ name: "Interview Flow Redesign", description: "Reduced recruiter scheduling friction", technologies: ["Figma"] }],
      certifications: [],
      languages: ["English", "Spanish"],
      resumeUrl: "https://example.com/resumes/leo-martinez.pdf",
      availability: "1 month",
    },
  ]);

  const jobs = await Job.insertMany([
    {
      recruiterId: recruiter._id,
      companyId: company._id,
      title: "Frontend Developer",
      department: "Engineering",
      openings: 2,
      employmentType: "Full-time",
      workplaceType: "Hybrid",
      location: "Austin, TX",
      summary:
        "We are hiring a frontend developer to build accessible, high-quality product experiences across recruiter and candidate workflows. The role requires strong collaboration, a practical product mindset, and attention to performance and usability.",
      responsibilities: ["Build recruiter-facing dashboards", "Collaborate with design and backend teams", "Improve performance and accessibility"],
      requiredQualifications: ["2+ years in frontend engineering", "Strong React fundamentals"],
      preferredQualifications: ["Experience with TypeScript", "Experience with charts and dashboards"],
      requiredSkills: ["React", "JavaScript", "CSS", "Git"],
      preferredSkills: ["TypeScript", "Recharts"],
      minimumEducation: "Bachelor's degree",
      minimumExperience: 2,
      maximumExperience: 5,
      certifications: [],
      languages: ["English"],
      salary: {
        minimum: 90000,
        maximum: 120000,
        currency: "USD",
        period: "Yearly",
        showPublicly: true,
      },
      applicationDeadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20),
      screeningQuestions: ["Describe a dashboard you built recently.", "How do you approach accessibility?"],
      requireResume: true,
      requireCoverLetter: false,
      applicationInstructions: "Share links to recent frontend work where possible.",
      status: "Published",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10),
      views: 132,
    },
    {
      recruiterId: recruiter._id,
      companyId: company._id,
      title: "AI Product Manager",
      department: "Product",
      openings: 1,
      employmentType: "Full-time",
      workplaceType: "Remote",
      location: "Remote",
      summary:
        "Lead product strategy for AI-powered workflow features, partnering closely with design, engineering, and go-to-market teams to shape reliable product experiences from discovery through launch.",
      responsibilities: ["Own roadmap", "Write clear product requirements", "Lead cross-functional launches"],
      requiredQualifications: ["3+ years in product management", "Experience with B2B SaaS"],
      preferredQualifications: ["AI product experience"],
      requiredSkills: ["Product Strategy", "Roadmapping", "Stakeholder Management"],
      preferredSkills: ["AI", "Experimentation"],
      minimumEducation: "Bachelor's degree",
      minimumExperience: 3,
      maximumExperience: 7,
      certifications: [],
      languages: ["English"],
      salary: {
        minimum: 125000,
        maximum: 160000,
        currency: "USD",
        period: "Yearly",
        showPublicly: false,
      },
      applicationDeadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
      screeningQuestions: ["What AI product have you shipped recently?"],
      requireResume: true,
      requireCoverLetter: true,
      applicationInstructions: "Include a short note about product impact metrics.",
      status: "Draft",
      views: 18,
    },
    {
      recruiterId: recruiter._id,
      companyId: company._id,
      title: "Technical Recruiter",
      department: "People",
      openings: 1,
      employmentType: "Contract",
      workplaceType: "Remote",
      location: "San Francisco, CA",
      summary:
        "Support hiring across engineering and product by driving candidate pipelines, managing interview coordination, and improving recruiting operations with a strong candidate experience mindset.",
      responsibilities: ["Source candidates", "Coordinate interviews", "Track pipeline health"],
      requiredQualifications: ["2+ years in technical recruiting"],
      preferredQualifications: ["Startup experience"],
      requiredSkills: ["Recruiting", "Sourcing", "Communication"],
      preferredSkills: ["ATS", "Scheduling"],
      minimumEducation: "Bachelor's degree",
      minimumExperience: 2,
      maximumExperience: 6,
      certifications: [],
      languages: ["English"],
      salary: {
        minimum: 45,
        maximum: 65,
        currency: "USD",
        period: "Hourly",
        showPublicly: true,
      },
      applicationDeadline: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
      screeningQuestions: ["What hiring funnel metrics do you watch most closely?"],
      requireResume: true,
      requireCoverLetter: false,
      applicationInstructions: "",
      status: "Published",
      publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40),
      views: 89,
    },
  ]);

  const applications = await Application.insertMany([
    {
      jobId: jobs[0]._id,
      candidateId: candidates[0]._id,
      recruiterId: recruiter._id,
      resumeUrl: candidates[0].resumeUrl,
      coverLetter: "I enjoy building recruiter workflows that feel polished and efficient.",
      screeningAnswers: [{ question: "Describe a dashboard you built recently.", answer: "I built a hiring analytics dashboard for an internal recruiting team." }],
      status: "Shortlisted",
      matchAnalysis: {
        overallScore: 84,
        scores: { skills: 44, experience: 16, education: 9, projects: 11, preference: 4 },
        matchedSkills: ["React", "JavaScript", "Git"],
        missingSkills: ["Recharts"],
        explanation: "The candidate has strong frontend experience and strong alignment with required skills.",
        recommendationLabel: "AI recommendation only",
        lastAnalyzedAt: new Date(),
      },
      appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
      shortlistedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    },
    {
      jobId: jobs[0]._id,
      candidateId: candidates[1]._id,
      recruiterId: recruiter._id,
      resumeUrl: candidates[1].resumeUrl,
      coverLetter: "I’ve built full-stack SaaS products and enjoy working across frontend and backend.",
      screeningAnswers: [{ question: "How do you approach accessibility?", answer: "I start with semantic structure and keyboard navigation first." }],
      status: "Under Review",
      matchAnalysis: {
        overallScore: 81,
        scores: { skills: 36, experience: 16, education: 9, projects: 11, preference: 9 },
        matchedSkills: ["React"],
        missingSkills: ["CSS", "Git"],
        explanation: "The candidate brings strong breadth and could still be a fit after deeper review.",
        recommendationLabel: "AI recommendation only",
        lastAnalyzedAt: new Date(),
      },
      appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
    },
    {
      jobId: jobs[2]._id,
      candidateId: candidates[2]._id,
      recruiterId: recruiter._id,
      resumeUrl: candidates[2].resumeUrl,
      coverLetter: "I care a lot about candidate experience and structured feedback loops.",
      screeningAnswers: [{ question: "What hiring funnel metrics do you watch most closely?", answer: "Time to fill and stage conversion rates." }],
      status: "Applied",
      appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
    },
  ]);

  await Interview.create({
    applicationId: applications[0]._id,
    jobId: jobs[0]._id,
    candidateId: candidates[0]._id,
    recruiterId: recruiter._id,
    title: "Frontend Developer Technical Interview",
    startDateTime: new Date(Date.now() + 1000 * 60 * 60 * 48),
    duration: 60,
    timezone: "America/Chicago",
    interviewType: "Technical",
    interviewerName: "Riya Sharma",
    interviewerEmail: "recruiter@novaedge.ai",
    meetingLink: "https://meet.example.com/frontend-round",
    location: "",
    notes: "Focus on collaboration and frontend architecture.",
    status: "Scheduled",
  });

  await Resume.insertMany([
    {
      candidateId: candidates[0]._id,
      originalName: "aarav-patel-resume.pdf",
      privateFileKey: "seed-aarav-resume",
      resumeUrl: candidates[0].resumeUrl,
      mimeType: "application/pdf",
      fileSize: 245760,
      isDefault: true,
      processingStatus: "Completed",
      analysisStatus: "Completed",
      extractedData: {
        name: candidates[0].name,
        phone: candidates[0].phone,
        skills: candidates[0].skills,
      },
      confirmedData: {
        name: candidates[0].name,
        phone: candidates[0].phone,
        skills: candidates[0].skills,
      },
      analysis: {
        overallScore: 81,
        sectionScores: {
          summary: 78,
          skills: 86,
          experience: 80,
          projects: 79,
          education: 82,
        },
        strengths: ["Strong skills coverage", "Clear work history"],
        improvements: ["Add more quantified project outcomes"],
        recommendedRoles: ["Frontend Engineer", "UI Engineer"],
        suggestedKeywords: ["React", "TypeScript", "Accessibility"],
      },
      visibility: {
        useForApplications: true,
        visibleAfterApplication: true,
        discoverableByVerifiedRecruiters: false,
        keepPrivate: true,
      },
      uploadedAt: new Date(Date.now() - 12 * 86400000),
    },
    {
      candidateId: candidates[1]._id,
      originalName: "maya-chen-resume.pdf",
      privateFileKey: "seed-maya-resume",
      resumeUrl: candidates[1].resumeUrl,
      mimeType: "application/pdf",
      fileSize: 262144,
      isDefault: true,
      processingStatus: "Completed",
      analysisStatus: "Completed",
      extractedData: {
        name: candidates[1].name,
        phone: candidates[1].phone,
        skills: candidates[1].skills,
      },
      confirmedData: {
        name: candidates[1].name,
        phone: candidates[1].phone,
        skills: candidates[1].skills,
      },
      analysis: {
        overallScore: 84,
        sectionScores: {
          summary: 82,
          skills: 88,
          experience: 83,
          projects: 80,
          education: 85,
        },
        strengths: ["Good full-stack skill depth", "Strong experience alignment"],
        improvements: ["Add more impact metrics to projects"],
        recommendedRoles: ["Full Stack Developer", "Platform Engineer"],
        suggestedKeywords: ["Node.js", "MongoDB", "TypeScript"],
      },
      visibility: {
        useForApplications: true,
        visibleAfterApplication: true,
        discoverableByVerifiedRecruiters: false,
        keepPrivate: true,
      },
      uploadedAt: new Date(Date.now() - 9 * 86400000),
    },
  ]);

  await SavedJob.insertMany([
    {
      candidateId: candidates[0]._id,
      jobId: jobs[0]._id,
      savedAt: new Date(Date.now() - 2 * 86400000),
    },
    {
      candidateId: candidates[0]._id,
      jobId: jobs[2]._id,
      savedAt: new Date(Date.now() - 1 * 86400000),
    },
  ]);

  await Notification.insertMany([
    {
      userId: candidateUsers[0]._id,
      userRole: "candidate",
      category: "Application update",
      title: "You were shortlisted",
      message: "Your Frontend Developer application was moved to Shortlisted.",
      relatedEntityType: "application",
      relatedEntityId: applications[0]._id.toString(),
      actionUrl: `/candidate/applications/${applications[0]._id}`,
      read: false,
    },
    {
      userId: candidateUsers[0]._id,
      userRole: "candidate",
      category: "Interview scheduled",
      title: "Technical interview scheduled",
      message: "Your Frontend Developer technical interview is scheduled for the upcoming round.",
      relatedEntityType: "interview",
      relatedEntityId: applications[0]._id.toString(),
      actionUrl: "/candidate/interviews",
      read: false,
    },
    {
      userId: candidateUsers[0]._id,
      userRole: "candidate",
      category: "Assessment result",
      title: "Assessment result available",
      message: "Your technical assessment result is now available to review.",
      relatedEntityType: "assessment-result",
      relatedEntityId: "attempt-result",
      actionUrl: "/candidate/assessments",
      read: true,
    },
  ]);

  await CandidatePrivacySettings.insertMany([
    {
      candidateId: candidates[0]._id,
      profileVisibility: "Visible only to companies I apply to",
      resumeVisibility: "Private",
    },
    {
      candidateId: candidates[1]._id,
      profileVisibility: "Discoverable by verified recruiters",
      resumeVisibility: "Visible only for submitted applications",
    },
  ]);

  const subscriptionPlans = await SubscriptionPlan.insertMany([
    {
      name: "Free Trial",
      code: "free-trial",
      description: "Trial plan for early evaluation.",
      monthlyPrice: 0,
      yearlyPrice: 0,
      currency: "USD",
      limits: {
        recruiterSeats: 1,
        activeJobs: 1,
        candidateInvitations: 25,
        resumeAnalyses: 50,
        aiQuestionGenerations: 20,
        codingExecutions: 50,
        proctoringMinutes: 0,
        storageGB: 1,
        emailNotifications: 200,
      },
      features: {
        codingAssessments: false,
        cameraMonitoring: false,
        questionBank: false,
        customBranding: false,
        advancedAnalytics: false,
        auditLogs: false,
        apiAccess: false,
        singleSignOn: false,
      },
      trialDays: 14,
      displayOrder: 1,
    },
    {
      name: "Starter",
      code: "starter",
      description: "For small recruiting teams.",
      monthlyPrice: 79,
      yearlyPrice: 790,
      currency: "USD",
      limits: {
        recruiterSeats: 3,
        activeJobs: 5,
        candidateInvitations: 500,
        resumeAnalyses: 500,
        aiQuestionGenerations: 200,
        codingExecutions: 1000,
        proctoringMinutes: 300,
        storageGB: 5,
        emailNotifications: 2500,
      },
      features: {
        codingAssessments: true,
        cameraMonitoring: false,
        questionBank: true,
        customBranding: false,
        advancedAnalytics: false,
        auditLogs: false,
        apiAccess: false,
        singleSignOn: false,
      },
      trialDays: 14,
      displayOrder: 2,
    },
    {
      name: "Growth",
      code: "growth",
      description: "For scaling recruiting teams.",
      monthlyPrice: 199,
      yearlyPrice: 1990,
      currency: "USD",
      limits: {
        recruiterSeats: 10,
        activeJobs: 20,
        candidateInvitations: 2500,
        resumeAnalyses: 2500,
        aiQuestionGenerations: 1000,
        codingExecutions: 5000,
        proctoringMinutes: 1500,
        storageGB: 20,
        emailNotifications: 12000,
      },
      features: {
        codingAssessments: true,
        cameraMonitoring: true,
        questionBank: true,
        customBranding: true,
        advancedAnalytics: true,
        auditLogs: true,
        apiAccess: false,
        singleSignOn: false,
      },
      trialDays: 14,
      displayOrder: 3,
    },
    {
      name: "Enterprise",
      code: "enterprise",
      description: "Custom enterprise plan.",
      monthlyPrice: 499,
      yearlyPrice: 4990,
      currency: "USD",
      limits: {
        recruiterSeats: 100,
        activeJobs: 500,
        candidateInvitations: 50000,
        resumeAnalyses: 50000,
        aiQuestionGenerations: 20000,
        codingExecutions: 50000,
        proctoringMinutes: 10000,
        storageGB: 200,
        emailNotifications: 100000,
      },
      features: {
        codingAssessments: true,
        cameraMonitoring: true,
        questionBank: true,
        customBranding: true,
        advancedAnalytics: true,
        auditLogs: true,
        apiAccess: true,
        singleSignOn: true,
      },
      trialDays: 7,
      displayOrder: 4,
    },
  ]);

  const subscription = await Subscription.create({
    organizationId: company._id,
    planId: subscriptionPlans[1]._id,
    provider: "stripe",
    providerCustomerId: "cus_demo_novaedge",
    providerSubscriptionId: "sub_demo_novaedge",
    status: "Active",
    billingCycle: "monthly",
    currentPeriodStart: new Date(Date.now() - 10 * 86400000),
    currentPeriodEnd: new Date(Date.now() + 20 * 86400000),
    trialStart: new Date(Date.now() - 24 * 86400000),
    trialEnd: new Date(Date.now() - 10 * 86400000),
    nextBillingDate: new Date(Date.now() + 20 * 86400000),
  });

  await BillingProfile.create({
    organizationId: company._id,
    legalName: "NovaEdge AI Inc.",
    billingEmail: "billing@novaedge.ai",
    billingPhone: "+1 415 555 0100",
    address: "425 Market Street",
    taxNumber: "US-TAX-001",
    country: "United States",
    state: "California",
    city: "San Francisco",
    postalCode: "94105",
  });

  await PaymentMethod.create({
    organizationId: company._id,
    providerPaymentMethodId: "pm_demo_visa",
    type: "card",
    brand: "Visa",
    lastFour: "4242",
    expiryMonth: 12,
    expiryYear: new Date().getFullYear() + 2,
    isDefault: true,
  });

  await Invoice.create({
    organizationId: company._id,
    subscriptionId: subscription._id,
    providerInvoiceId: "inv_demo_1001",
    invoiceNumber: "NE-1001",
    planName: "Starter",
    amount: 79,
    discount: 0,
    tax: 6,
    totalAmount: 85,
    currency: "USD",
    status: "Paid",
    billingPeriodStart: subscription.currentPeriodStart,
    billingPeriodEnd: subscription.currentPeriodEnd,
    invoiceUrl: "https://example.com/invoices/ne-1001.pdf",
    paidAt: new Date(Date.now() - 8 * 86400000),
  });

  await Coupon.create({
    code: "GROWTH20",
    discountType: "percentage",
    discountValue: 20,
    currency: "USD",
    validFrom: new Date(Date.now() - 30 * 86400000),
    validUntil: new Date(Date.now() + 30 * 86400000),
    maximumRedemptions: 100,
    redemptionCount: 2,
    applicablePlanIds: [subscriptionPlans[1]._id, subscriptionPlans[2]._id],
    minimumAmount: 50,
    firstPaymentOnly: true,
    active: true,
  });

  await CreditBalance.insertMany([
    {
      organizationId: company._id,
      creditType: "aiQuestionCredits",
      purchased: 100,
      used: 24,
      remaining: 76,
      expiresAt: new Date(Date.now() + 120 * 86400000),
    },
    {
      organizationId: company._id,
      creditType: "codingExecutionCredits",
      purchased: 500,
      used: 90,
      remaining: 410,
      expiresAt: new Date(Date.now() + 120 * 86400000),
    },
  ]);

  await CreditTransaction.insertMany([
    {
      organizationId: company._id,
      creditType: "aiQuestionCredits",
      transactionType: "purchase",
      quantity: 100,
      source: "seed",
      expiresAt: new Date(Date.now() + 120 * 86400000),
    },
    {
      organizationId: company._id,
      creditType: "codingExecutionCredits",
      transactionType: "purchase",
      quantity: 500,
      source: "seed",
      expiresAt: new Date(Date.now() + 120 * 86400000),
    },
  ]);

  await UsageRecord.insertMany([
    {
      organizationId: company._id,
      subscriptionId: subscription._id,
      resourceType: "activeJobs",
      quantity: 2,
      billingPeriodStart: subscription.currentPeriodStart,
      billingPeriodEnd: subscription.currentPeriodEnd,
      metadata: {},
    },
    {
      organizationId: company._id,
      subscriptionId: subscription._id,
      resourceType: "candidateInvitations",
      quantity: 37,
      billingPeriodStart: subscription.currentPeriodStart,
      billingPeriodEnd: subscription.currentPeriodEnd,
      metadata: {},
    },
    {
      organizationId: company._id,
      subscriptionId: subscription._id,
      resourceType: "resumeAnalyses",
      quantity: 18,
      billingPeriodStart: subscription.currentPeriodStart,
      billingPeriodEnd: subscription.currentPeriodEnd,
      metadata: {},
    },
    {
      organizationId: company._id,
      subscriptionId: subscription._id,
      resourceType: "aiQuestionGenerations",
      quantity: 12,
      billingPeriodStart: subscription.currentPeriodStart,
      billingPeriodEnd: subscription.currentPeriodEnd,
      metadata: {},
    },
    {
      organizationId: company._id,
      subscriptionId: subscription._id,
      resourceType: "codingExecutions",
      quantity: 51,
      billingPeriodStart: subscription.currentPeriodStart,
      billingPeriodEnd: subscription.currentPeriodEnd,
      metadata: {},
    },
  ]);

  const questionBankItems = await QuestionBankItem.insertMany([
    {
      organizationId: company._id,
      recruiterId: recruiter._id,
      questionText: "Which React hook should you use to store local component state?",
      questionType: "MCQ",
      source: "Question Bank",
      skill: "React",
      topic: "Hooks",
      difficulty: "Easy",
      marks: 2,
      negativeMarks: 0.5,
      tags: ["react", "hooks"],
      mcq: {
        options: [
          { id: "a", text: "useState" },
          { id: "b", text: "useEffect" },
          { id: "c", text: "useRef" },
          { id: "d", text: "useContext" },
        ],
        correctOptionIds: ["a"],
      },
      expectedAnswer: "useState",
      answerExplanation: "useState is used for local component state.",
    },
    {
      organizationId: company._id,
      recruiterId: recruiter._id,
      questionText: "Fix the syntax error in the JavaScript snippet.",
      questionType: "Syntax and Debugging",
      source: "Manual",
      skill: "JavaScript",
      topic: "Syntax",
      difficulty: "Medium",
      marks: 5,
      negativeMarks: 0,
      technicalPrompt: {
        programmingLanguage: "JavaScript",
        codeSnippet: "const total = (a, b => a + b;",
        instructions: "Correct the code and explain the issue.",
        expectedAnswer: "const total = (a, b) => a + b;",
        alternativeAcceptedAnswers: ["function total(a, b) { return a + b; }"],
      },
      expectedAnswer: "const total = (a, b) => a + b;",
      answerExplanation: "The closing parenthesis was missing before the arrow.",
    },
  ]);

  const assessments = await Assessment.insertMany([
    {
      organizationId: company._id,
      recruiterId: recruiter._id,
      jobId: jobs[0]._id,
      title: "Frontend Developer Technical Assessment",
      description: "Multi-section assessment for frontend candidates.",
      category: "Technical",
      experienceLevel: "Entry level",
      assessmentLanguage: "English",
      candidateInstructions:
        "Please complete all mandatory sections. AI or integrity flags are only reviewed by recruiters and do not automatically decide outcomes.",
      sections: [
        {
          title: "Frontend Foundations",
          description: "Core React and JavaScript knowledge",
          type: "MCQ",
          duration: 20,
          numberOfQuestions: 2,
          totalMarks: 4,
          passingScore: 2,
          negativeMarking: true,
          sectionOrder: 1,
          isMandatory: true,
          questions: [
            {
              questionText: questionBankItems[0].questionText,
              questionType: "MCQ",
              skill: "React",
              topic: "Hooks",
              difficulty: "Easy",
              marks: 2,
              negativeMarks: 0.5,
              source: "Question Bank",
              options: questionBankItems[0].mcq.options,
              correctOptionIds: questionBankItems[0].mcq.correctOptionIds,
              multipleCorrect: false,
              answerExplanation: questionBankItems[0].answerExplanation,
            },
            {
              questionText: "Which CSS layout is best for one-dimensional alignment?",
              questionType: "MCQ",
              skill: "CSS",
              topic: "Layout",
              difficulty: "Easy",
              marks: 2,
              negativeMarks: 0.5,
              source: "Manual",
              options: [
                { id: "a", text: "Flexbox" },
                { id: "b", text: "Float" },
                { id: "c", text: "Table layout" },
                { id: "d", text: "Position absolute" },
              ],
              correctOptionIds: ["a"],
              multipleCorrect: false,
              answerExplanation: "Flexbox is designed for one-dimensional alignment.",
            },
          ],
        },
        {
          title: "Debugging and Coding",
          description: "Debug and solve practical problems",
          type: "Coding Test",
          duration: 35,
          numberOfQuestions: 2,
          totalMarks: 15,
          passingScore: 8,
          negativeMarking: false,
          sectionOrder: 2,
          isMandatory: true,
          questions: [
            {
              questionText: questionBankItems[1].questionText,
              questionType: "Syntax and Debugging",
              skill: "JavaScript",
              topic: "Syntax",
              difficulty: "Medium",
              marks: 5,
              negativeMarks: 0,
              source: "Question Bank",
              programmingLanguage: "JavaScript",
              codeSnippet: questionBankItems[1].technicalPrompt.codeSnippet,
              expectedAnswer: questionBankItems[1].expectedAnswer,
              alternativeAcceptedAnswers: questionBankItems[1].technicalPrompt.alternativeAcceptedAnswers,
              answerExplanation: questionBankItems[1].answerExplanation,
            },
            {
              questionText: "Build a function that returns the sum of two integers from a space-separated input string.",
              questionType: "Coding Test",
              skill: "JavaScript",
              topic: "Functions",
              difficulty: "Medium",
              marks: 10,
              negativeMarks: 0,
              source: "Manual",
              problemTitle: "Sum Two Integers",
              problemStatement: "Given a string with two integers separated by a space, return their sum.",
              inputFormat: "A single string like '2 3'",
              outputFormat: "Single integer result",
              constraints: "Inputs are valid integers",
              sampleInput: "2 3",
              sampleOutput: "5",
              allowedLanguages: ["JavaScript", "Python", "Java", "C++"],
              starterCode: {
                JavaScript: "function solve(input) {\n  const [a, b] = input.trim().split(/\\s+/).map(Number);\n  return String(a + b);\n}",
                Python: "def solve(input_data):\n    a, b = map(int, input_data.split())\n    return str(a + b)\n",
              },
              visibleTestCases: [{ input: "2 3", output: "5", explanation: "Simple sum" }],
              hiddenTestCases: [{ input: "10 20", output: "30" }],
              timeLimit: 2,
              memoryLimit: 128,
              answerExplanation: "Use string parsing and return the sum.",
            },
          ],
        },
      ],
      settings: {
        totalDuration: 55,
        overallPassingPercentage: 60,
        maximumAttempts: 1,
        assessmentStartDate: new Date(Date.now() - 2 * 86400000),
        assessmentEndDate: new Date(Date.now() + 30 * 86400000),
        invitationLinkExpiry: new Date(Date.now() + 7 * 86400000),
        autoSubmitWhenTimeEnds: true,
        allowCandidateReviewPreviousAnswers: true,
        allowCandidateChangeAnswersBeforeSubmission: true,
        allowCalculator: false,
        allowCodeExecution: true,
        requireResume: true,
        requireCandidateEmailVerification: true,
        requireCandidateConsent: true,
        showResultImmediately: true,
        allowRetake: false,
        retakeWaitingPeriod: 0,
      },
      resumeMatchSettings: {
        requiredSkills: ["React", "JavaScript", "CSS", "Git"],
        strongMatchThreshold: 75,
        partialMatchThreshold: 45,
        allowRecruiterOverride: true,
        lastOutcomeLabel: "Strong Match",
      },
      integritySettings: {
        fullScreenMode: true,
        tabSwitchMonitoring: true,
        browserFocusMonitoring: true,
        copyDetection: true,
        pasteDetection: true,
        rightClickMonitoring: true,
        multipleSessionDetection: true,
        multipleDeviceDetection: true,
        ipChangeDetection: true,
        questionRandomization: true,
        answerOptionRandomization: true,
        oneTimeInvitationTokens: true,
        codeSimilarityDetection: true,
        cameraMonitoring: false,
      },
      resultVisibility: {
        showCompleteResult: true,
        showOverallScoreOnly: true,
        showSectionScores: true,
        showPassFailOnly: true,
        hideResultUntilRecruiterReview: false,
        showCorrectAnswers: true,
      },
      status: "Published",
      totalDuration: 55,
      totalMarks: 19,
      passingPercentage: 60,
      lastAutoSavedAt: new Date(),
    },
    {
      organizationId: company._id,
      recruiterId: recruiter._id,
      jobId: jobs[1]._id,
      title: "AI Product Manager Screen",
      description: "Reusable PM screening assessment draft.",
      category: "General screening",
      experienceLevel: "Intermediate",
      assessmentLanguage: "English",
      candidateInstructions: "Complete the screening questions thoughtfully. Results are reviewed by recruiters.",
      sections: [
        {
          title: "PM Basics",
          description: "Product reasoning and communication",
          type: "Short Answer",
          duration: 15,
          numberOfQuestions: 1,
          totalMarks: 5,
          passingScore: 3,
          negativeMarking: false,
          sectionOrder: 1,
          isMandatory: true,
          questions: [
            {
              questionText: "Describe how you would validate an AI workflow feature before launch.",
              questionType: "Short Answer",
              skill: "Product Strategy",
              topic: "Validation",
              difficulty: "Medium",
              marks: 5,
              negativeMarks: 0,
              source: "Manual",
              expectedAnswer: "A strong answer covers user research, prototype testing, success metrics, and rollout risks.",
              answerExplanation: "Recruiter review required.",
            },
          ],
        },
      ],
      settings: {
        totalDuration: 15,
        overallPassingPercentage: 60,
        maximumAttempts: 1,
        assessmentStartDate: new Date(Date.now() - 1 * 86400000),
        assessmentEndDate: new Date(Date.now() + 14 * 86400000),
        invitationLinkExpiry: new Date(Date.now() + 5 * 86400000),
        autoSubmitWhenTimeEnds: true,
        allowCandidateReviewPreviousAnswers: true,
        allowCandidateChangeAnswersBeforeSubmission: true,
        allowCalculator: false,
        allowCodeExecution: false,
        requireResume: true,
        requireCandidateEmailVerification: true,
        requireCandidateConsent: true,
        showResultImmediately: false,
        allowRetake: false,
        retakeWaitingPeriod: 0,
      },
      resumeMatchSettings: {
        requiredSkills: ["Product Strategy", "Roadmapping", "Stakeholder Management"],
        strongMatchThreshold: 75,
        partialMatchThreshold: 45,
        allowRecruiterOverride: true,
        lastOutcomeLabel: "Partial Match",
      },
      integritySettings: {
        fullScreenMode: false,
        tabSwitchMonitoring: true,
        browserFocusMonitoring: true,
        copyDetection: false,
        pasteDetection: false,
        rightClickMonitoring: false,
        multipleSessionDetection: true,
        multipleDeviceDetection: true,
        ipChangeDetection: true,
        questionRandomization: false,
        answerOptionRandomization: false,
        oneTimeInvitationTokens: true,
        codeSimilarityDetection: false,
        cameraMonitoring: false,
      },
      resultVisibility: {
        showCompleteResult: false,
        showOverallScoreOnly: true,
        showSectionScores: false,
        showPassFailOnly: true,
        hideResultUntilRecruiterReview: true,
        showCorrectAnswers: false,
      },
      status: "Draft",
      totalDuration: 15,
      totalMarks: 5,
      passingPercentage: 60,
      lastAutoSavedAt: new Date(),
    },
  ]);

  const invitations = await AssessmentInvitation.insertMany([
    {
      organizationId: company._id,
      recruiterId: recruiter._id,
      assessmentId: assessments[0]._id,
      jobId: jobs[0]._id,
      candidateId: candidates[0]._id,
      candidateName: candidates[0].name,
      candidateEmail: candidates[0].email,
      invitationToken: "frontend-aarav-invite-token",
      status: "Completed",
      expiresAt: new Date(Date.now() + 7 * 86400000),
      maxAttempts: 1,
      attemptsUsed: 1,
      sentAt: new Date(Date.now() - 6 * 86400000),
      openedAt: new Date(Date.now() - 5 * 86400000),
      resumeSubmittedAt: new Date(Date.now() - 5 * 86400000),
      startedAt: new Date(Date.now() - 5 * 86400000),
      completedAt: new Date(Date.now() - 5 * 86400000),
      emailVerificationCode: "123456",
      emailVerifiedAt: new Date(Date.now() - 5 * 86400000),
    },
    {
      organizationId: company._id,
      recruiterId: recruiter._id,
      assessmentId: assessments[0]._id,
      jobId: jobs[0]._id,
      candidateId: candidates[1]._id,
      candidateName: candidates[1].name,
      candidateEmail: candidates[1].email,
      invitationToken: "frontend-maya-invite-token",
      status: "Sent",
      expiresAt: new Date(Date.now() + 6 * 86400000),
      maxAttempts: 1,
      attemptsUsed: 0,
      sentAt: new Date(Date.now() - 1 * 86400000),
      emailVerificationCode: "123456",
    },
  ]);

  const attempt = await AssessmentAttempt.create({
    organizationId: company._id,
    recruiterId: recruiter._id,
    assessmentId: assessments[0]._id,
    invitationId: invitations[0]._id,
    candidateId: candidates[0]._id,
    candidateProfile: {
      name: candidates[0].name,
      email: candidates[0].email,
      phone: candidates[0].phone,
      skills: candidates[0].skills,
      education: candidates[0].education,
      experience: candidates[0].experience,
      projects: candidates[0].projects,
      certifications: candidates[0].certifications,
      resumeUrl: candidates[0].resumeUrl,
    },
    resumeMatch: {
      status: "Strong Match",
      score: 82,
      matchedSkills: ["React", "JavaScript", "CSS"],
      missingSkills: ["Git"],
      explanation: "Candidate has strong relevant frontend skills and experience.",
      recruiterOverride: false,
    },
    answers: [
      {
        questionId: assessments[0].sections[0].questions[0]._id,
        sectionId: assessments[0].sections[0]._id,
        questionType: "MCQ",
        selectedOptionIds: ["a"],
        score: 2,
      },
      {
        questionId: assessments[0].sections[0].questions[1]._id,
        sectionId: assessments[0].sections[0]._id,
        questionType: "MCQ",
        selectedOptionIds: ["a"],
        score: 2,
      },
      {
        questionId: assessments[0].sections[1].questions[0]._id,
        sectionId: assessments[0].sections[1]._id,
        questionType: "Syntax and Debugging",
        answerText: "const total = (a, b) => a + b;",
        score: 4,
        aiSuggestedScore: 4,
      },
      {
        questionId: assessments[0].sections[1].questions[1]._id,
        sectionId: assessments[0].sections[1]._id,
        questionType: "Coding Test",
        score: 8,
        codingSubmission: {
          programmingLanguage: "JavaScript",
          code: "function solve(input) { const [a,b]=input.trim().split(/\\s+/).map(Number); return String(a+b); }",
          executionResults: {
            passedTestCases: 1,
            failedTestCases: 0,
            totalTestCases: 1,
            executionTime: 88,
            memoryUsage: 24,
            compilerOutput: "All visible test cases passed.",
            visibleResults: [{ input: "2 3", expectedOutput: "5", actualOutput: "5", passed: true }],
          },
          submissionHistory: [
            {
              code: "function solve(input) { const [a,b]=input.trim().split(/\\s+/).map(Number); return String(a+b); }",
              language: "JavaScript",
              submittedAt: new Date(Date.now() - 5 * 86400000),
              passedTestCases: 1,
              failedTestCases: 0,
            },
          ],
          codeSimilarityWarning: false,
        },
      },
    ],
    sectionResults: [
      { sectionId: assessments[0].sections[0]._id, title: "Frontend Foundations", score: 4, totalMarks: 4 },
      { sectionId: assessments[0].sections[1]._id, title: "Debugging and Coding", score: 12, totalMarks: 15 },
    ],
    totalScore: 16,
    passingStatus: true,
    recruiterRecommendation: "Strong technical performance",
    completionTimeMinutes: 42,
    attemptNumber: 1,
    recruiterReview: {
      status: "Reviewed",
      note: "Strong score and clean code solution.",
      reviewedAt: new Date(Date.now() - 4 * 86400000),
    },
    integritySummary: {
      status: "Low Concern",
      totalFlags: 2,
      tabSwitches: 1,
      focusLosses: 1,
      fullScreenExits: 0,
      copyAttempts: 0,
      pasteAttempts: 0,
      cameraInterruptions: 0,
      candidateAbsenceFlags: 0,
      multiplePeopleFlags: 0,
      deviceChanges: 0,
      ipChanges: 0,
      codeSimilarityFlags: 0,
    },
    activityTimeline: [
      { label: "Assessment started", metadata: {}, createdAt: new Date(Date.now() - 5 * 86400000) },
      { label: "Tab switched", metadata: { count: 1 }, createdAt: new Date(Date.now() - 5 * 86400000 + 15 * 60000) },
      { label: "Window focus lost", metadata: {}, createdAt: new Date(Date.now() - 5 * 86400000 + 24 * 60000) },
      { label: "Assessment submitted", metadata: {}, createdAt: new Date(Date.now() - 5 * 86400000 + 42 * 60000) },
    ],
    status: "Submitted",
    startedAt: new Date(Date.now() - 5 * 86400000),
    submittedAt: new Date(Date.now() - 5 * 86400000 + 42 * 60000),
  });

  await IntegrityEvent.insertMany([
    {
      organizationId: company._id,
      invitationId: invitations[0]._id,
      attemptId: attempt._id,
      eventType: "Tab switched",
      severity: "low",
      metadata: { atQuestion: "Which CSS layout is best for one-dimensional alignment?" },
      createdAt: new Date(Date.now() - 5 * 86400000 + 15 * 60000),
      updatedAt: new Date(Date.now() - 5 * 86400000 + 15 * 60000),
    },
    {
      organizationId: company._id,
      invitationId: invitations[0]._id,
      attemptId: attempt._id,
      eventType: "Window focus lost",
      severity: "low",
      metadata: {},
      createdAt: new Date(Date.now() - 5 * 86400000 + 24 * 60000),
      updatedAt: new Date(Date.now() - 5 * 86400000 + 24 * 60000),
    },
  ]);

  console.log("Seed completed successfully.");
  await mongoose.connection.close();
}

seed().catch(async (error) => {
  console.error("Seed failed", error);
  await mongoose.connection.close();
  process.exit(1);
});
